### ISSUE TITLE
Images loaded from Disk Cache occasionally display artifacts / corruption.

### ISSUE THREAD

**Issue by baby03201** [pinterest/PINRemoteImage#260]
I'm currently using AsyncDisplayKit + PINRemoteImage libraries in my app.
The PINRemoteImage version is 3.0.0-beta.3 (due to some constraint using in AsyncDisplayKit)

This library is awesome, however, sometimes the cached images look not fully downloaded as the image below:
![broken](https://cloud.githubusercontent.com/assets/923188/19639675/fed3c2be-9a0b-11e6-802b-17ce8b2923bc.jpeg)

The function I'm using is 

```
UIImageView *imageView = [[UIImageView alloc] init];
[imageView setPin_updateWithProgress:YES];
[imageView pin_setImageFromURL:[NSURL URLWithString:@"$(my_image_link)"]];
```

**Comment by garrettmoon** [comment]
@baby03201 I have a guess as to the cause of that:
Are you running in the simulator. I've seen similar issues when running in the simulator, but *never* on device.

**Comment by appleguy** [comment]
It is possible that there is an encoding error or other issue with the image file.  Could you send the URL to the image of that size?

**Comment by baby03201** [comment]
@garrettmoon Unfortunately, I couldn't able to regenerate that error in my device now. This screenshot was taken by my friend with his iPhone 6s device. I guess it might happens while the network connection is bad.

@appleguy Thanks for your patience and response!
The images URL link was shown as below:
[First image](http://resource.golface.com.tw/ADPlatform/image/ALBA%E9%9B%9C%E8%AA%8C/2016%E5%B9%B49%E6%9C%88/alba-mag-cover201609.jpg)
[Second image](http://resource.golface.com.tw/ADPlatform/image/ALBA%E9%9B%9C%E8%AA%8C/2016%E5%B9%B48%E6%9C%88/alba-mag-cover201608.jpg)

**Comment by SteveGeyer** [comment]
I came here looking specifically for information this bug. We just upgraded AsyncDisplayKit from 1.9.81 to 1.9.91 and similarly got PINRemoteImage upgraded to 3.0.0-beta.3. We we started seeing bad images on live devices (not the simulator) and we had not previously been seeing them in the three months we have been using this product. We started focussing on PINRemoteImage when we realize that the problem occurred with images fully managed and rendered by AsyncDisplayKit as well as by code where we called PINRemoteImage directly to load other images.

We are not doing progressive downloads and I have attached one such image that failed. That exact same image worked perfectly on many other devices so it is not a simple data corruption issue.

The AsyncDisplayKit version of this problem using ASNetworkImageNode controlled by a layoutSpecThatFits(). When we call PINRemoteImage directly we are using:

`        imageView.pin_setImageFromURL(NSURL(string: look.imageUrl!),
                                      completion: { [weak self] (_) in
            self?.spinner.removeFromSuperview()
        })
`

We really appreciate all the great work Facebook has done on this amazing product and hope it will continue. We would also appreciate any insight we can get on how to fix this bug.

![badimage](https://cloud.githubusercontent.com/assets/805451/19975808/bfc2736c-a1c3-11e6-9ace-6d7f9efd107f.jpg)

**Comment by garrettmoon** [comment]
Hey @SteveGeyer thanks for the info!

Do you happen to know what version of PINRemoteImage you were using previously? 1.9.81 specified beta 2 or better. Can you confirm that's what you were using?

A note: This is actually a Pinterest project and all the full time contributors on AsyncDisplayKit are also Pinterest employees :)

**Comment by SteveGeyer** [comment]
@garrettmoon Yes I was using beta 2.

I apologize for my mistake on credit. PINRemoteImage and AsyncDisplayKit are awesome products. They have made our app truly sing. I really appreciate all the work you and the Pinterest staff has put into them.

**Comment by garrettmoon** [comment]
@SteveGeyer Awesome, ok, I'll see if there's something that could help attribute the difference. And no worries about the misattribution :)

**Comment by garrettmoon** [comment]
Here are the changes between beta 2 and beta 3 (https://github.com/pinterest/PINRemoteImage/compare/3.0.0-beta.2...3.0.0-beta.3) 

My first guess is it has to do with the cancelation patch. Possibly something getting a callback after cancelation.
https://github.com/pinterest/PINRemoteImage/commit/2cfc232d117a746f2004f61cefc2326149c63443

**Comment by SteveGeyer** [comment]
I am not exactly sure what you may be suggesting. However, the image I provided in my initial post was one that is rendered by AsyncDisplayKit. You are seeing one cell (ASCellNode) made up of three images and some other stuff. This cell's layout is controlled by layoutSpecThatFits() and this cell is in a collection of many cells (ASCollectionView). The AsyncDisplayKit prefetch on the ASCollectionView may in fact be calling cancel on early cells once you scroll too far forward.

One question, if it is being cancelled shouldn't that remove the image completely from the cache? Once we have a damaged image we can't get rid of it. Restarting the app does nothing. Since the app does not have a "clear the cache" feature, the users had to remove the app and reload it to fix the image.

Unfortunately I have not been able to get this to happen on demand. One of my team managed it several time and at least one of our beta testers has seen it. I personally have only seen screenshots. If your theory is correct, is there any way you can suggest that would make provoking it more likely. I would gladly give it a try and get back to you.

My other question is whatever going to beta 5 is likely to fix it. If I revert to 1.9.81 it fetches beta 5 now (sadly 1.9.92 does not -- it is fixed at beta 3). Do you believe beta 5 would help or hurt or just be neutral.

Thanks for all your help.

**Comment by garrettmoon** [comment]
@SteveGeyer my guess is that beta 5 won't have this issue fixed. I'm going to see if I can set up some conditions which will allow me to reproduce locally.

**Comment by garrettmoon** [comment]
@SteveGeyer there could be another issue causing this: if an image isn't fully saved to the disk cache when the app is terminated it could result in something like this. It would be good to know if when the issue is reproduced for the first time, if it was pulling the image from the cache or from the network. Not sure an easy way to confirm that either though…

**Comment by garrettmoon** [comment]
@SteveGeyer actually, if you happen to know if the version of PINCache changed when you upgraded, knowing which version to which would help in investigating.

**Comment by SteveGeyer** [comment]
@garrettmoon I have grabbed my Podfile.lock from the "working" system and edited out unnecessary pods. Below are what I believe are the relevant lines. It shows PINCache 2.2.2.

PODS:
  - AsyncDisplayKit (1.9.81):
    - AsyncDisplayKit/PINRemoteImage (= 1.9.81)
  - AsyncDisplayKit/ASDealloc2MainObject (1.9.81)
  - AsyncDisplayKit/Core (1.9.81):
    - AsyncDisplayKit/ASDealloc2MainObject
  - AsyncDisplayKit/PINRemoteImage (1.9.81):
    - AsyncDisplayKit/Core
    - PINRemoteImage/iOS (>= 3.0.0-beta.2)
  - PINCache (2.2.2)
  - PINRemoteImage/Core (3.0.0-beta.2):
    - PINCache (>= 2.1)
  - PINRemoteImage/iOS (3.0.0-beta.2):
    - PINRemoteImage/Core
  - pop (1.0.9)

I talked to my coworker who is very experienced with the app and he assures me that it did not crash nor did he stop the app part the way through. I completely trust his report. He also kept his device in its broken state so I could bring up a debugger and run code against the cache. Would this help you?

As to your question on where the image was coming from. It was most likely coming from the network and not the cache. None of the images preexist in the app. The image in my example above would have been from AsyncDisplayKits's prefetch of cells and that would have initially come from the network. You see the TOMORROW at the top. I talked to him and he had just flipped to the tomorrow page to do QA on tomorrow's content delivery. He would have flipped to this page, waited for the screen to load from the network, and then reviewed this piece of content. It got stuck downloading the image.

**Comment by garrettmoon** [comment]
@SteveGeyer very valuable information, thank you! I'm investigating this as we speak :)

**Comment by garrettmoon** [comment]
@stevegeyer there would be one more valuable piece of information you could gather for me. Specifically the file that's stored in the cache. You should be able to get to it by calling objectForKey with the offending URL on the cache object of `[PINRemoteImageManager sharedImageManager]` (the key you pass in can be retrieved by calling `[[PINRemoteImageManager sharedImageManager] cacheKeyForURL:URL processorKey:nil]`

Knowing the URL would also be helpful.

Finally, one more question: are you attempting to use PINRemoteImage anywhere else in the app directly? Or are you just using the ASDK implementation?

**Comment by SteveGeyer** [comment]
I am off to a meeting right now, but will grab this data and answer your questions in a couple of hours.

**Comment by SteveGeyer** [comment]
@garrettmoon I will attempt to get the local cache file tomorrow when I
have access to the actual device that failed. I will also try and get you
the URLs involved.

We are definitely calling PINRemoteImage directly elsewhere in the app. In
fact those calls are likely happening at the same time as ASDK. The URLs
used by ASDK and direct calls will different since ASDK is handling the
thumbnails while the direct calls are fetching the full image for later use.

**Comment by SteveGeyer** [comment]
@garrettmoon The damaged image that I showed in my original post has "repaired" itself since yesterday. I assume that its expiration timed out and it was refetched. However, there is another image that is failing and I have attached an image of this failure to the bottom of this message.

Here is the source URL for this failing image: https://s3.amazonaws.com/lookbk/imgs/01/fe/dD/tP/01fedDtP-LRfQaBOI6.jpg

I ran `[[PINRemoteImageManager sharedImageManager] cacheKeyForURL:URL processorKey:nil]` in the app and I get the same URL back (https://s3.amazonaws.com/lookbk/imgs/01/fe/dD/tP/01fedDtP-LRfQaBOI6.jpg).

At the same time as we were fetching these thumbnails from ASDK, we are likely fetching larger versions of these images with a direct calls to PINRemoteImage. In this example, the image can be found at https://s3.amazonaws.com/lookbk/imgs/01/fe/dD/tP/01fedDtP-dofJvaQiV.jpg

While I was in this code I realized that I do limit the size of the cache:

> let imageCache = PINRemoteImageManager.sharedImageManager().cache.diskCache
> imageCache.byteLimit = imageCacheSize
> imageCache.ageLimit = maxCacheTime`

The cache byteLimit was 495MB and the ageLimit is 2 weeks. The specific device that failed had been used for a long time so it is it possible we are hitting the size limit while loading the image?  Could this be an issue?

I hope all this helps. Thanks again for your help.

![badimage3](https://cloud.githubusercontent.com/assets/805451/20007951/eefca8ee-a274-11e6-9711-6f5d0193fc16.jpg)

**Comment by garrettmoon** [comment]
Can you also attach the corrupted image *from* the cache? so if cacheKeyForURL returned just the URL, you should be able to get the NSData out by calling `[[[PINRemoteImageManager sharedImageManager] cache] objectForKey:@"https://s3.amazonaws.com/lookbk/imgs/01/fe/dD/tP/01fedDtP-LRfQaBOI6.jpg"]`

Not sure the easiest way to get the NSData off the phone… Maybe try and write it to the Documents directory and get at it with iTunes file sharing (http://stackoverflow.com/questions/6029916/how-to-enable-file-sharing-for-my-app)? That's a bit of a pain, but I'd really appreciate it, I'm hoping it can confirm my theory.

**Comment by SteveGeyer** [comment]
@garrettmoon Sadly we reset the broken device. We will try and recreate the error and capture that image (I am all set up to do the capture once we have another failure).

**Comment by appleguy** [comment]
@SteveGeyer Just wanted to say thanks for how proactive you've been on bringing information to this thread.  It's extremely helpful.  We haven't seen a corruption issue like this in Pinterest, so it is really important that we capture any clues we can to prevent it for others.

Could you share a bit more about how you're using PINRemoteImage?  I have a feeling that the issue is caused by interacting with two different PINRemoteImageManagers at the same time, about the same resource — e.g. one might be trying to read it from the cache, while the other is writing.  This may not be the case (or a problem), since I think they share a disk cache instance, but it could be the difference in configuration that means Pinterest doesn't see the issue.  If it is related to having multiple instances, we will have a much better lead on fixing it.

@garrettmoon would there be any benefit in using the ASPINRemoteImageManager +sharedInstance?  IIRC that's how you can get the instance that ASDK uses.  Maybe that would avert the issue, and if so, we'd have a good lead.

**Comment by SteveGeyer** [comment]
I am going to overshare here in the hopes that what I write sparks ideas on your side. I have grepped our source code and I will outline each direct call we make to PINCache and PINRemoteCache. Our app is written totally in Swift. I doubt that is significant, but maybe your team knows something I don't. We are also big fans of ASDK and PINCache/PINRemoteCache and we are using all three products directly (and of course ASDK uses PINCache/PINRemoteCache internally).

For this discussion it is important to know that our app shows a list of potential articles you can view using ASDK. ASDK, through ASNetworkImageNode()s with their URL set,  is responsible for fetching thumbnail images used in the summary pages. The intelligent preloading logic of ASKD is used by us to fetch the full images of the article using PINRemoteImage. The important point here is that ASDK fetches thumbnails while our manual calls to PINRemoteImage fetch full sized images. They are fundamentally different URLs. There is a single exception to this rule that I will get to later.

Since we are using PIN caches for both JSON and images, we set up cache limits at startup:

> let jsonCache = PINCache.sharedCache().diskCache
> jsonCache.byteLimit = jsonCacheSize
> jsonCache.ageLimit = maxCacheTime
> let imageCache = PINRemoteImageManager.sharedImageManager().cache.diskCache
> imageCache.byteLimit = imageCacheSize
> imageCache.ageLimit = maxCacheTime

jsonCacheSize is 5MB, imageCacheSize is 495MB and ageLimit is 2 weeks.

The two lines of code we use store and retrieve JSON are:
> PINCache.sharedCache().objectForKey(key)
> PINCache.sharedCache().setObject(data, forKey: key)

Intelligent preloading has us prefetching the full size images the the following line. We usually fetch between 10-20 images each time:
> uuids = PINRemoteImageManager.sharedImageManager().prefetchImagesWithURLs(imageURLs)

If the preloading logic says we are abandoning this article, we cancel any remaining fetches with:
> for uuid in uuids {
>  PINRemoteImageManager.sharedImageManager().cancelTaskWithUUID(uuid)
> }

Note again that these are full sized image with different URLs from the thumbnails fully managed by ASDK.

Like I said earlier, we have one UI controller that prefetches the same thumbnails that ASDK fetches. It uses:
> uuids = PINRemoteImageManager.sharedImageManager().prefetchImagesWithURLs(imageURLs)

Here the imageURLs list is thumbnails. However, these thumbnails are not being used in active articles. So it is not possible that they duplicate one of the thumbnails being fetched by ASDK.

For completeness, If that controller sees the cell leaving the view it cancels the fetch with.
> for uuid in uuids {
>  PINRemoteImageManager.sharedImageManager().cancelTaskWithUUID(uuid)
> }

This represents all calls that we make directly to PINCache and PINRemoteImage. While I believe we are frequently mixing calls of ASDK fetches with direct fetches, I believe the URLs used by ASDK are different than the ones we manually fetch using PINRemoteImage.

I will gladly attempt to answer any other questions you may have.

**Comment by appleguy** [comment]
This is very helpful Steve, thank you!

Before diving in with further suggestions, I'll let Garrett think through this feedback - and especially whether multiple ImageManagers could interact in a negative way (even with distinct URLs).

One tip: you can achieve the same preloading effect by using an offscreen ASNetworkImageNode that you trigger to perform its preloading.  You can do this by setting its .interfaceState to Preload.  We could add an API to make that a bit easier :).

There's also ASMultiplexImageNode, which works especially well if you want to take an image / thumbnail and zoom it up in an animation; it can perform the downloading and decoding of a higher resolution version asynchronously, even as the onscreen version is being animated.  It also uses the best-fit disk cache version while trying to load the high res, so it would automatically show an upscaled thumbnail version if the high-res request is still in flight (this might be desirable for your app).

**Comment by SteveGeyer** [comment]
@garrettmoon I am set up to dump a broken image as you previously requested. Unfortunately our failed images were automatically refreshed after their time-to-live expired and we have not seen this problem reoccur. If we see another failure I will capture the image for you.

This brings up some potential evidence about this bug. We saw three failures across two long term users shortly after they upgraded to our newest version with the upgraded PINRemoteImage. We have not had any other errors reported (although our beta users are not always the best at reporting issues).

So I wondered if the issue could be related to upgrading the library. Did the cache storage format subtly change in a manner that has a small hiccup with pre-existing and fully loaded caches? My other ponder was if it could be related to the cache being at its max limits. Both of these users would have had the image cache at their limit with each new image requiring the cache eject one or more previous images. Maybe there is a subtle issue there. Finally, since these failures only happened in one short window of time, I wonder if there was some subtle issue with our hosted images and them causing the caching code to receive some unusual network error. All of these are just idle speculations from an interested user, so use or ignore these as appropriate.

We are getting near our initial release and have to decide what to do next. Do we roll back our versions of ASDK and the PIN caches? Do we move forward on the assumption these were some special kind of failure that won't happen regularly to normal users (either it was upgrade related or network failure related)? Or do we move forward assuming you will find and post a fix shortly? Any feedback you can bring to this decision would be greatly appreciated.

I thank you again for all the work you are doing to resolve this.

**Comment by garrettmoon** [comment]
@SteveGeyer All reasonable theories and to be honest I still haven't been able to find any conclusive to point to anything. As @appleguy mentioned, we haven't seen reports of these errors at Pinterest, but we're on latest master (or very close) of ASDK, PINRemoteImage and PINCache.

To be frank, I wouldn't rely on us being able to post a fix shortly. I believe this is a very important issue to get to the bottom of, but without a solid way to reproduce, I'm not sure I can promise a quick fix.

If I were in your situation I'd probably monitor to see if it comes up again. If it doesn't stick with what you have, if it does I would attempt to mitigate what is possibly the cause:

1. Use only one instance of PINRemoteImage, the one created by ASPINRemoteImageDownloader. We do this in Pinterest by creating a category which we use instead of PINRemoteImageManager:

```
+ (PINRemoteImageManager *)sharedImageManager
{
    return [[ASPINRemoteImageDownloader sharedDownloader] sharedPINRemoteImageManager];
}
```

**Comment by garrettmoon** [comment]
And please keep reporting back :)

**Comment by SteveGeyer** [comment]
@garrettmoon We will consider your advise as we move forward. If anything else happens at our end I will post what happened and what we did. Thanks.

**Comment by garrettmoon** [comment]
@SteveGeyer thank you! All the info you've given us is going to definitely narrow down solving this issue. Hopefully very soon :)

**Comment by boreys** [comment]
I am experiencing the same issue in a country where internet connection is slow, unreliable and when there are multiple concurrent image requests (around 60 images per screen view).
![6f17725a-a5ba-11e6-8fb5-7b423beb36ab](https://cloud.githubusercontent.com/assets/8430251/20096092/e1f24dc0-a5da-11e6-812c-8824d5c34328.jpg)

**Comment by garrettmoon** [comment]
@boreys what version of PINRemoteImage are you using? Do you have a test app you can reliably reproduce the issue on? If so, I should be able to simulate a similar internet connection.

**Comment by boreys** [comment]
I'm using PINRemoteImage 3.0.0-beta.3 and 'AsyncDisplayKit', '~>1.9.90' you can download my app from the store and follow this step, it most likely produce the result ( a couple broken images):
1- Download the app: https://itunes.apple.com/us/app/khmer.be/id1138606309?ls=1&mt=8
2- Create an account and follow some users to generate around 60 images or more on the "News Feed" page. 
3- Log out, uninstall the app and then reinstall the app so that the cache is removed from device.
5- Turn Network Conditioner on with the worst condition: slow and interrupting
6- Log in to the app to download fresh images on the News Feed, which should aggressively download the images and generate some broken ones

Mean while I'm gonna try to debug this library myself too.

**Comment by jaichaudhry** [comment]
@garrettmoon  I am also facing the same issue. The images are getting corrupted in the same fasion as the screenshot attached by @boreys

**Comment by garrettmoon** [comment]
Whoo! I think we finally got this one licked! I'll update this thread when I've pushed a new beta for you all to try.

**Comment by garrettmoon** [comment]
Going to close this as it should be fixed in PINRemoteImage (`3.0.0-beta.7`) & ASDK (`2.0-rc.2`). Please give it a try and if you hit this again mention it here.

**Comment by SteveGeyer** [comment]
Thanks for fixing the bug. I will be trying the fix out shortly.

**Comment by emablekos** [comment]
Just wanted to let you know we experience this from time to time. I just got it on this file:
https://170213-images.liketoknow.it/791cd8d0-19a4-11e7-9fed-0242ac110002?fm=pjpg&q=75&w=345&fit=max

I mounted the phone with iExplorer and pulled it off disk:
![busted](https://cloud.githubusercontent.com/assets/299982/25510985/08f0312a-2b92-11e7-8e22-ca479843f03f.jpg)

This screenshot represents how it renders on the phone:
![image](https://cloud.githubusercontent.com/assets/299982/25510996/260da6ac-2b92-11e7-912f-a8630b76c682.png)

We are on:
PINRemoteImage (3.0.0-beta.8)

It is pretty rare.

**Comment by appleguy** [comment]
This is a very helpful report - thanks for sending it. I know that beta.9
is now available, but am not sure if it has changes intended to resolve
this. It would be worth updating just in case, but I think the frequency of
this issue has reduced even though it is still sometimes happening.

I'm pretty sure that if the app crashes or is killed (as might happen when
developing / debugging too), we could write a corrupted file if it is in
progress at the time of the kill. It's an interesting question on how we
might detect and discard these.

**Comment by marcinwlodarczyk** [comment]
I'm experiencing the same issue but on one device only (iPhone 6, iOS 12.0). First we noticed this problem on the latest master release, then I tried with the beta version `3.0.0-beta.7` and it still persists (we tried a clean install to make sure that the corrupted image is not taken still from a cache).
Have you traced the root cause of this issue? 

All I'm doing is just running the following code:
`[self.broadcastImageView pin_setImageFromURL: url placeholderImage: [UIImage imageNamed: @"broadcast_loading"]];`
and this is called on a main thread originally from `UICollectionViewDataSource` method:
`- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath;`

![img_0423](https://user-images.githubusercontent.com/17600239/51391919-b5452380-1b33-11e9-86d6-2d24c0952ecf.PNG)

**Comment by garrettmoon** [comment]
@marcinwlodarczyk are you hitting it frequently? I wonder if it could have something to do with resume support on canceled images…

**Comment by marcinwlodarczyk** [comment]
@garrettmoon on that device we were getting this problem ~70% of times (clean launches). I've just tried your lates beta release `(3.0.0-beta.10)` and this problem seems to disappear. Scanning quickly changes that have been made in your (great) framework since the `beta.6` release I think this issue could be related to simultaneous download of multiple images and maybe even to downloading an image again before the previous download operation completed (of the same image) - which could potentially happen.
Great news is that this problem does not occur anymore for me now. Thank you guys for fixing this issue and for the sharing this great lib with a community.

**Comment by garrettmoon** [comment]
Glad to hear it's not affecting you all anymore!
